/* Anwendungskontext: Produktion von Schuhen 
Gruppenmitglieder: Fabian Eckert 7221608
David Bauschulte 7220824
*/

drop table mitarbeiter cascade constraints;
drop table produktionsabteilung cascade constraints;
drop table produktionsauftrag cascade constraints;
drop table kunde cascade constraints;
drop table bearbeitet_pm cascade constraints;
drop table bearbeitet_pp cascade constraints;
drop table schuhmodell cascade constraints;
drop table produktionsansprechpartner cascade constraints;
drop table material cascade constraints;
drop table liefert cascade constraints;
drop table lieferant cascade constraints;
drop table standort cascade constraints;



create table produktionsabteilung (
   abteilungs_id     integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   abteilungsname    varchar(30) unique not null,
   hauptabteilung_id integer,
   foreign key ( hauptabteilung_id )
      references produktionsabteilung ( abteilungs_id )
);

create table mitarbeiter (
   mitarbeiter_id integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   vorname        varchar(20) not null,
   nachname       varchar(20) not null,
   abteilungs_id  integer,
   foreign key ( abteilungs_id )
      references produktionsabteilung ( abteilungs_id )
);
create table kunde (
   kunden_id integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   vorname   varchar(20) not null,
   nachname  varchar(20) not null
);

create table schuhmodell (
   modell_id  integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   typ        varchar(20) not null,
   modellname varchar(30) not null
);

create table produktionsauftrag (
   auftrags_id   integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   auftragsdatum date not null,
   groesse       integer not null,
   farbe         varchar(20) not null,
   gesamtstatus  varchar(50) not null check ( gesamtstatus in ( 'In Bearbeitung',
                                                               'Abgeschlossen',
                                                               'Storniert' ) ),
   kunden_id     integer not null,
   modell_id     integer not null,
   foreign key ( kunden_id )
      references kunde ( kunden_id ),
   foreign key ( modell_id )
      references schuhmodell ( modell_id )
);

create table bearbeitet_pm (
   auftrags_id    integer,
   mitarbeiter_id integer,
   foreign key ( auftrags_id )
      references produktionsauftrag ( auftrags_id ),
   foreign key ( mitarbeiter_id )
      references mitarbeiter ( mitarbeiter_id ),
   primary key ( auftrags_id,
                 mitarbeiter_id )
);



create table bearbeitet_pp (
   status        varchar(20) not null check ( status in ( 'In Bearbeitung',
                                                   'Erledigt' ) ),
   auftrags_id   integer,
   abteilungs_id integer,
   foreign key ( auftrags_id )
      references produktionsauftrag ( auftrags_id ),
   foreign key ( abteilungs_id )
      references produktionsabteilung ( abteilungs_id ),
   primary key ( auftrags_id,
                 abteilungs_id )
);

create table produktionsansprechpartner (
   produktionsansprechpartner_id integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   vorname                       varchar(20) not null,
   nachname                      varchar(20) not null,
   telefonnummer                 integer not null,
   email                         varchar(40) not null,
   abteilungs_id                 integer,
   foreign key ( abteilungs_id )
      references produktionsabteilung ( abteilungs_id )
);

create table lieferant (
   lieferant_id  integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   email         varchar(40) not null check ( regexp_like ( email,
                                                    '^\S+@[\.A-Za-z]+$' ) ),
   nachname      varchar(20) not null,
   vorname       varchar(20) not null,
   telefonnummer varchar(15) not null,
   firmenname    varchar(30) not null
);

create table standort (
   standort_id    integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   strassennummer integer not null,
   strasse        varchar(30) not null,
   postleitzahl   integer not null,
   lieferant_id   integer,
   foreign key ( lieferant_id )
      references lieferant ( lieferant_id )
);

create table material (
   material_id   integer generated by default as identity ( start with 1 increment by 1 ) primary key,
   materialname  varchar(30) not null,
   lagerbestand  integer not null check ( lagerbestand >= 0 ) check ( lagerbestand between 1 and 500 ),
   lagerort      varchar(30) not null,
   abteilungs_id integer,
   foreign key ( abteilungs_id )
      references produktionsabteilung ( abteilungs_id )
);

create table liefert (
   anzahl       integer not null,
   material_id  integer,
   lieferant_id integer,
   primary key ( material_id,
                 lieferant_id ),
   foreign key ( material_id )
      references material ( material_id ),
   foreign key ( lieferant_id )
      references lieferant ( lieferant_id )
);


-- Ebene 1
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (1, 'Zuschnitt', NULL);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (2, 'Nähen', NULL);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (3, 'Montage', NULL);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (4, 'Versand', NULL);

-- Ebene 2 (Kinder von 4)
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (5, 'Verpackung', 4);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (6, 'Warenausgang', 4);

-- Ebene 3 (Kinder von 5 und 6)
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (7, 'Etikettieren', 5);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (8, 'Einschweißen', 5);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (9, 'Kommissionierung', 6);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (10, 'Verladung', 6);

-- Ebene 4 (Kinder von 8 und 10)
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (11, 'Palettieren', 8);
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (12, 'Spedition', 10);

-- Ebene 5 (Kind von 11)
INSERT INTO produktionsabteilung (abteilungs_id, abteilungsname, hauptabteilung_id) VALUES (13, 'Sicherung', 11);

-- 2. Mitarbeiter
INSERT INTO mitarbeiter (vorname, nachname, abteilungs_id) VALUES ('Tim', 'Müller', 1);
INSERT INTO mitarbeiter (vorname, nachname, abteilungs_id) VALUES ('Max', 'Schmidt', 1);
INSERT INTO mitarbeiter (vorname, nachname, abteilungs_id) VALUES ('Hans', 'Peter', 2);

-- 3. Kunden
INSERT INTO kunde (vorname, nachname) VALUES ('Otto', 'Backfisch');
INSERT INTO kunde (vorname, nachname) VALUES ('Katharina', 'Tünnemann');
INSERT INTO kunde (vorname, nachname) VALUES ('Monica', 'Hartung');

-- 4. Schuhmodelle
INSERT INTO schuhmodell (typ, modellname) VALUES ('Sneaker', 'Air');
INSERT INTO schuhmodell (typ, modellname) VALUES ('Stiefel', 'Salvus');
INSERT INTO schuhmodell (typ, modellname) VALUES ('High-Heels', 'Valentino');

-- 5. Produktionsaufträge
INSERT INTO produktionsauftrag (auftragsdatum, groesse, farbe, gesamtstatus, kunden_id, modell_id) 
VALUES (TO_DATE('01.01.2025', 'DD.MM.YYYY'), 44, 'Blau', 'In Bearbeitung', 1, 1);
INSERT INTO produktionsauftrag (auftragsdatum, groesse, farbe, gesamtstatus, kunden_id, modell_id) 
VALUES (TO_DATE('01.02.2025', 'DD.MM.YYYY'), 43, 'Gruen', 'In Bearbeitung', 2, 2);
INSERT INTO produktionsauftrag (auftragsdatum, groesse, farbe, gesamtstatus, kunden_id, modell_id) 
VALUES (TO_DATE('01.10.2024', 'DD.MM.YYYY'), 33, 'Rot', 'Abgeschlossen', 3, 1);
INSERT INTO produktionsauftrag (auftragsdatum, groesse, farbe, gesamtstatus, kunden_id, modell_id) 
VALUES (TO_DATE('01.05.2025', 'DD.MM.YYYY'), 42, 'Schwarz', 'In Bearbeitung', 1, 1);
-- 6. Relation Bearbeitet (Mitarbeiter <-> Auftrag)
INSERT INTO bearbeitet_pm (auftrags_id, mitarbeiter_id) VALUES (1, 1);
INSERT INTO bearbeitet_pm (auftrags_id, mitarbeiter_id) VALUES (1, 2);
INSERT INTO bearbeitet_pm (auftrags_id, mitarbeiter_id) VALUES (2, 3);

-- 7. Relation Bearbeitet (Abteilung <-> Auftrag)
INSERT INTO bearbeitet_pp (auftrags_id, abteilungs_id, status) VALUES (1, 1, 'In Bearbeitung');
INSERT INTO bearbeitet_pp (auftrags_id, abteilungs_id, status) VALUES (2, 1, 'Erledigt');
INSERT INTO bearbeitet_pp (auftrags_id, abteilungs_id, status) VALUES (3, 2, 'In Bearbeitung');
INSERT INTO bearbeitet_pp (auftrags_id, abteilungs_id, status) VALUES (4, 1, 'In Bearbeitung');
-- 8. Produktionsansprechpartner (Telefonnummer als Integer wie im Create Table)
INSERT INTO produktionsansprechpartner (vorname, nachname, telefonnummer, email, abteilungs_id) 
VALUES ('Fabian', 'Eckert', 1522123456, 'fabian.eckert@tti.de', 1);
INSERT INTO produktionsansprechpartner (vorname, nachname, telefonnummer, email, abteilungs_id) 
VALUES ('David', 'Bauschulte', 175345678, 'david.bauschulte@tti.de', 2);
INSERT INTO produktionsansprechpartner (vorname, nachname, telefonnummer, email, abteilungs_id) 
VALUES ('Mashad', 'Waleed', 179657899, 'mashad.waleed@tti.de', 3);

-- 9. Lieferant
INSERT INTO lieferant (email, nachname, vorname, telefonnummer, firmenname) 
VALUES ('fabian.swat@web.de', 'Swat', 'Fabian', '01522829299', 'Renus');
INSERT INTO lieferant (email, nachname, vorname, telefonnummer, firmenname) 
VALUES ('jonas.eckert@web.de', 'Eckert', 'Jonas', '015222435678', 'Molex');
INSERT INTO lieferant (email, nachname, vorname, telefonnummer, firmenname) 
VALUES ('john.haase@molex.de', 'Haase', 'John', '01797894940', 'Yageo');

-- 10. Standort
INSERT INTO standort (strassennummer, strasse, postleitzahl, lieferant_id) VALUES (20, 'Wiehagen', 45560, 1);
INSERT INTO standort (strassennummer, strasse, postleitzahl, lieferant_id) VALUES (35, 'Mühlenstraße', 59199, 2);
INSERT INTO standort (strassennummer, strasse, postleitzahl, lieferant_id) VALUES (10, 'Brachtstraße', 59368, 3);
INSERT INTO standort (strassennummer, strasse, postleitzahl, lieferant_id) VALUES (6, 'Roggenkamp', 59368, 2);
INSERT INTO standort (strassennummer, strasse, postleitzahl, lieferant_id) VALUES (15, 'Flachskamp', 59368, 3);
-- 11. Material
INSERT INTO material (materialname, lagerbestand, lagerort, abteilungs_id) VALUES ('Leder', 200, 'Regal 1', 1);
INSERT INTO material (materialname, lagerbestand, lagerort, abteilungs_id) VALUES ('Nylon', 100, 'Regal 2', 2);
INSERT INTO material (materialname, lagerbestand, lagerort, abteilungs_id) VALUES ('Gummi', 500, 'Regal 3', 3);
INSERT INTO material (materialname, lagerbestand, lagerort, abteilungs_id) VALUES ('Pappe', 400, 'Regal 4', 4);
INSERT INTO material (materialname, lagerbestand, lagerort, abteilungs_id) VALUES ('Kleber', 200, 'Regal 5', 5);
-- 12. Relation Liefert (Lieferant <-> Material)
INSERT INTO liefert (anzahl, material_id, lieferant_id) VALUES (20, 1, 1);
INSERT INTO liefert (anzahl, material_id, lieferant_id) VALUES (50, 2, 1);
INSERT INTO liefert (anzahl, material_id, lieferant_id) VALUES (100, 3, 2);

COMMIT;